### ISSUE TITLE
403 error 'Application Request limit reached'

### ISSUE THREAD

**Issue by dixonge** [danburzo/fb-export#3]
I did managed to download all my posts, but part of the way through image downloads this error popped up. Is there something I can adjust in my FB app settings to bypass this? Should I run the script again later?

**Comment by danburzo** [comment]
Yes, I think FB may be imposing some limits on the amount of requests you can do in a short while to the API. You may be able to download them if you try again later.

**Comment by dixonge** [comment]
8 hours later, same result. So it's not really too many hits in too short a time. Maybe they just don't like the script? Not sure...

**Comment by danburzo** [comment]
That's a bummer... Unfortunately I have since deleted by FB account and am reluctant to set up a new one to test it. Would love if someone could take a look at why it's failing!

Technically, if it's a rate-limiting kind of error, I think an easy fix would be to add a timeout before proceeding to the next request, e.g. here:

https://github.com/danburzo/fb-export/blob/57677ed156f1cafbfeba398747badeaed4d56958/tools/photos.js#L109

becomes: 

```js
setTimeout(() => { fetch_images(image_queue, callback) }, 300)
```
or another decent amount of milliseconds.

**Comment by dixonge** [comment]
last time I tried it failed on the first attempt, as if they have blocked it almost. I am now trying another script that takes FB's own data export download and then processes it from there (with the goal of importing certain posts/photos to my own blog)

**Comment by dixonge** [comment]
This should have been closed years ago... - also @danburzo FYI I finally deleted my FB account on March 5! :)

**Comment by danburzo** [comment]
Hah, that's great to hear! :-)
